---
- name: test sdapi ansible module
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
  - name: Add, Publish Firewall Policy and Update Devices
    sdapi:    
      junosspace_host: junosspace1.kdc.jnpr.net
      junosspace_username: super
      junosspace_password: juniper123
      change_request_id: ansible-cr123
      #device: labsrx
      #source_zone: lab
      source_addresses: ['172.27.169.3', '172.27.169.4']
      #destination_zone: jnpr
      destination_addresses: ['8.8.8.8', '8.8.4.4']
      services: ['icmp-ping'] 
      action: add
      publish: True
      update_devices: True
      change_control_workflow: True
